parameters:
  - name: enableSonar
    default: true
  - name: enableGitLeaks
    default: true
  - name: enableCodeScan
    default: false
  - name: buildType
    default: 'c'
  - name: buildType_W
    default: 'c_windows'
  - name: agentPool
    default: Dev
  - name: agentPool_Win
    default: Default
  - name: version_dll
    default: 64
  - name: sourcePath
    default: '.'
  - name: dotNetProjects
    default: 'csproj'

stages:
- ${{ if eq(parameters.enableSonar, true) }}:
    - stage: CheckRepository_${{ parameters.buildType }}
      jobs: 
        - job: Sonar_${{ parameters.buildType }}
          pool:
            name: ${{ parameters.agentPool }}
          steps:
            - template: Templates/checks/sonar.yaml
              parameters:
                buildType: ${{ parameters.buildType }}
                dotNetProjects: ${{ parameters.dotNetProjects }}
        - ${{ if eq(parameters.enableGitleaks, true) }}:
            - job: Gitleaks_${{ parameters.buildType }}
              pool:
                name: ${{ parameters.agentPool }}
              steps:
                - template: Templates/checks/gitleaks.yaml
        - ${{ if eq(parameters.enableCodeScan, true) }}:
            - job: CodeScan_${{ parameters.buildType }}
              pool:
                name: ${{ parameters.agentPool }}
              steps:
                - template: Templates/checks/slscan.yaml

- stage: BuildAndPush_${{ parameters.buildType }}
  jobs:
    - job: Build_${{ parameters.buildType }}
      pool:
        name: ${{ parameters.agentPool }}
      steps:
        - template: Templates/build/checkout.yaml
          parameters:
            buildType: ${{ parameters.buildType }}
            sourcePath: ${{ parameters.sourcePath }}
            dotNetProjects: ${{ parameters.dotNetProjects }}
        - template: Templates/publish/publish.yaml
          parameters:
            buildType: ${{ parameters.buildType }}

- stage: BuildAndPush_Windows${{ parameters.buildType_W }}
  jobs:
    - job: Build_${{ parameters.buildType_W }}
      pool:
        name: ${{ parameters.agentPool_Win }}
      steps:
      - template: Templates/build/checkout.yaml
        parameters:
          buildType_W: ${{ parameters.buildType_W }}
          version_dll: ${{ parameters.version_dll }}