parameters:
  - name: buildType
    default: 'c'
  - name: agentPoolWin
    default: Default
  - name: agentPool
    default: Dev
  - name: setor
    default: ''


stages:
   - ${{ if eq(parameters.buildType, 'c') }}:
      stage:
      jobs:
        - job: Build_${{ parameters.buildType }}
          pool:
            name: ${{ parameters.agentPool }}
          steps:
            - template: Templates/container/dockerRun.yaml
              parameters:
                buildType: ${{ parameters.buildType }}
                setor: ${{ parameters.setor }}
