parameters:
  - name: buildType
    default: 'dockerBuild'
  - name: agentPoolWin
    default: Default
  - name: agentPool
    default: Dev

stages:
   - ${{ if eq(parameters.buildType, 'dockerBuild') }}:
      stage:
      jobs:
        - job: Build_${{ parameters.buildType }}
          pool:
            name: ${{ parameters.agentPool }}
          steps:
            - template: Templates/conteiner/dockerRun.yaml
              parameters:
                buildType: ${{ parameters.buildType }}
