parameters:
  - name: enableSonar
    default: true
  - name: buildType
    default: 'c'
  - name: agentPool
    default: Dev
  - name: sourcePath
    default: '.'

stages:
- ${{ if eq(parameters.enableSonar, true) }}:
    - stage: CheckRepository_${{ parameters.buildType }}
      jobs: 
        - job: Sonar_${{ parameters.buildType }}
          pool:
            name: ${{ parameters.agentPool }}
          steps:
            - template: Templates/checks/sonar.yaml

- stage: BuildAndPush_${{ parameters.buildType }}
  jobs:
    - job: Build_${{ parameters.buildType }}
      pool:
        name: ${{ parameters.agentPool }}
      steps:
        - template: Templates/build/checkout.yaml
          parameters:
            buildType: ${{ parameters.buildType }}
            sourcePath: ${{ parameters.sourcePath }}
        - template: Templates/publish/publish.yaml
          parameters:
            buildType: ${{ parameters.buildType }}

