parameters:
  - name: skipChecks
    default: false
  - name: buildType
    default: 'c'

stages:
- ${{ if ne(parameters.skipChecks, false) }}:
    - stage: CheckRepository
      jobs:
        - template: Templates/checks/sonar.yaml

- stage: BuildAndPush
  jobs:
    - job: Build
      pool:
        name: Dev
      steps:
        - template: Templates/build/checkout.yaml
          parameters:
            buildType: ${{ parameters.buildType }}
        - template: Templates/publish/publish.yaml

