parameters:
  - name: enableSonar
    default: false
  - name: buildType
    default: 'c'
  - name: agentPool
    default: Dev

stages:
- ${{ if eq(parameters.enableSonar, true) }}:
    - stage: CheckRepository
      jobs: 
        - job: Sonar
          pool:
            name: ${{ parameters.agentPool }}
          steps:
            - template: Templates/checks/sonar.yaml

- stage: BuildAndPush
  jobs:
    - job: Build
      pool:
        name: ${{ parameters.agentPool }}
      steps:
        - template: Templates/build/checkout.yaml
          parameters:
            buildType: ${{ parameters.buildType }}
        - template: Templates/publish/publish.yaml

