parameters:
  - name: buildType
    default: 'Drivers'
  - name: agentPoolWin
    default: Default

stages:
  - ${{ if eq(parameters.buildType, 'Drivers') }}:
      stage:
      jobs:
        - job: Build_${{ parameters.buildType }}
          pool:
            name: ${{ parameters.agentPoolWin }}
          steps:
            - template: Templates/publish/publishNexus.yaml
              parameters:
                buildType: ${{ parameters.buildType }}

